# Generated by Django 4.0.3 on 2022-03-28 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_categorie_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modification_date',
        ),
    ]
